### ISSUE TITLE
ssh: Could not resolve hostname gitlab-master.nvidia.com: Name or service not known

### ISSUE THREAD

**Issue by CPFelix** [NVIDIA-AI-IOT/TAO-Toolkit-Whitepaper-use-cases#1]
When I use the cammand "git clone ssh://git@gitlab-master.nvidia.com:12051/sochoa/tao_experiments.git", I get the follow error:
"ssh: Could not resolve hostname gitlab-master.nvidia.com: Name or service not known",how to solve?Thanks!

**Comment by monjha** [comment]
Hi CPFelix,

Thanks for catching that. I updated the readme: please use: git@github.com:NVIDIA-AI-IOT/TAO-Toolkit-Whitepaper-use-cases.git

**Comment by CPFelix** [comment]
@monjha Sorry to interupt again.When I train the model,I get the follow error:
"AssertionError: matching_neutral_box_iou must be within (0.25, 1]"
Is it means the hyper-parameter have some problems?

**Comment by CPFelix** [comment]
I update the examples you proviede and use tao instead of tlt and train seccessfully.
